# Generated by Django 4.2.2 on 2023-07-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=50, null=True)),
                ('st_email', models.EmailField(max_length=70, null=True)),
                ('st_password', models.IntegerField(max_length=50, null=True)),
            ],
        ),
    ]
