# Generated by Django 4.2.2 on 2023-07-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regtable',
            old_name='st_email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='regtable',
            old_name='st_name',
            new_name='fname',
        ),
        migrations.RemoveField(
            model_name='regtable',
            name='st_password',
        ),
        migrations.AddField(
            model_name='regtable',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='regtable',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='regtable',
            name='fees',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='regtable',
            name='gen',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='regtable',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='regtable',
            name='mytext',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='regtable',
            name='password',
            field=models.IntegerField(null=True),
        ),
    ]
