# Generated by Django 4.2.2 on 2023-07-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_st_email_regtable_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regtable',
            old_name='password',
            new_name='Pass',
        ),
        migrations.AlterField(
            model_name='regtable',
            name='gen',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
