# Generated by Django 4.2.2 on 2023-07-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_password_regtable_pass_alter_regtable_gen'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegTable2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, null=True)),
                ('lname', models.CharField(max_length=50, null=True)),
                ('DOB', models.DateField(null=True)),
                ('gen', models.CharField(max_length=50, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Email', models.EmailField(max_length=70, null=True)),
                ('Pass', models.IntegerField(null=True)),
                ('mytext', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='regtable',
            name='fees',
        ),
    ]
