# Generated by Django 4.2.2 on 2023-07-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_regtable2_remove_regtable_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegTable3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, null=True)),
                ('lname', models.CharField(max_length=50, null=True)),
                ('DOB', models.DateField(null=True)),
                ('gen', models.CharField(max_length=50, null=True)),
                ('Payment_Method', models.CharField(max_length=50, null=True)),
                ('PayMethod', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
